AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  _api

  Sample SAM Template for _api

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10
  Api:
    Cors:
      AllowMethods: "'GET,POST,DELETE,OPTIONS'"
      AllowHeaders: "'content-type'"
      AllowOrigin: "'http://localhost:5173'"

Resources:
  GetNFTsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: get-nfts.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        ApiGatewayEvent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /
            Method: get
      Environment:
        Variables:
          ALLOW_ORIGIN: http://localhost:5173
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - get-nfts.ts
