AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  _api

  Sample SAM Template for _api

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Environment:
      Variables:
        ALLOW_ORIGIN: http://localhost:5173
    CodeUri: src/
    Runtime: nodejs18.x
    Architectures:
      - x86_64
  Api:
    Cors:
      AllowMethods: "'GET,POST,DELETE,OPTIONS'"
      AllowHeaders: "'content-type'"
      AllowOrigin: "'http://localhost:5173'"

Resources:
  GetNFTsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: get-nfts.lambdaHandler
      Events:
        ApiGatewayEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - get-nfts.ts
  PremintFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: premint.lambdaHandler
      Events:
        ApiGatewayEvent:
          Type: Api
          Properties:
            Path: /premint
            Method: post
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - premint.ts
